server {
    listen 80;
    server_name localhost;

    # EN KRİTİK SATIR: Nginx'in 8080 portunu silip 80'e yönlendirmesini yasaklar!
    absolute_redirect off;

    # Projenin ana klasörü
    root /usr/share/nginx/html;
    
    # CSS, JS, HTML gibi standart tipleri Nginx'e öğretir
    include /etc/nginx/mime.types;

    # 3D modeller için ekstra ayar
    types {
        model/gltf-binary glb;
    }

    # Sadece localhost:8080 yazıldığında doğru alt klasöre (portu kaybetmeden) yönlendirir
    location = / {
        return 302 /panoromic_visit_builder/frontend/index.html;
    }

    # Dosyaları arama ve bulma mantığı
    location / {
        try_files $uri $uri/ =404;
    }
}